# ~/.tmuxinator/neubbs.yml

name: neubbs
root: ~/Developer/code/neubbs/src/main/webapp

windows:
  - editor: vim
  - shell:
      layout: even-horizontal
      panes:
        - npm run watch
        - clear
